### ISSUE TITLE
[Bug] hook will only work when CWD is the directory of this repo.

### ISSUE THREAD

**Issue by serco-chen** [broly8/letsencrypt-aliyun-dns-manual-hook#2]
https://github.com/broly8/letsencrypt-aliyun-dns-manual-hook/blob/2bfaaacbefaf588df59007e7371c53940923efea/manual-hook.py#L15

To reproduce, run `certbot` from elsewhere other than the directory of this repo.

**Comment by broly8** [comment]
@serco-chen Fixed it. Thank you! [3f9c89a](https://github.com/broly8/letsencrypt-aliyun-dns-manual-hook/commit/3f9c89ab1470218e2c9806da8dcd51a105eab81c)
