### ISSUE TITLE
【支持】请问这个能否自动部署到阿里云的SSL托管里面？

### ISSUE THREAD

**Issue by qzm** [broly8/letsencrypt-aliyun-dns-manual-hook#7]
我期待的是这个可以定时运行一下，申请新的证书，然后部署到阿里云的SSL托管里面，这样CDN之类的就可以直接使用了，毕竟证书申请下来之后，还需要部署一下，部署才是比较麻烦的地方。

**Comment by broly8** [comment]
@qzm 本工具不支持上传证书。阿里云有提供上传证书的API，有兴趣请自行研究哦。链接：https://help.aliyun.com/document_detail/126507.html
