### ISSUE TITLE
python3无法执行，但python2正常

### ISSUE THREAD

**Issue by BA7JCM** [broly8/letsencrypt-aliyun-dns-manual-hook#8]
我一开始没装python2，用的系统自带的python3，结果报错“2021-10-01 16:16:29,406 logger ERROR ("'AttributeError' object has no attribute 'message'",)”，安装python2之后改用python2执行就正常了

**Comment by broly8** [comment]
暂时没有测试环境，晚点搭建好再测试一下

**Comment by broly8** [comment]
@BA7JCM @whc2001 已做兼容https://github.com/broly8/letsencrypt-aliyun-dns-manual-hook/commit/c354975fafa32b7bb3717f2e9c2fc093fb312d60

> 我一开始没装python2，用的系统自带的python3，结果报错“2021-10-01 16:16:29,406 logger ERROR ("'AttributeError' object has no attribute 'message'",)”，安装python2之后改用python2执行就正常了

**Comment by whc2001** [comment]
```
ERROR module 'base64' has no attribute 'encodestring'
```

encodestring 在 Python 3.1 后已弃用，已由 #9 修复

**Comment by broly8** [comment]
> ```
> ERROR module 'base64' has no attribute 'encodestring'
> ```
> 
> encodestring 在 Python 3.1 后已弃用，已由 #9 修复

已合并，感谢
